apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentfront
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 1
  template:
    metadata:
      labels:
        app: Employee
    spec:
      containers:
        - name: employeeangular
          image: wetmonkey/angular-app:latest
          ports:
            - containerPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentback
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 1
  template:
    metadata:
      labels:
        app: Employee
    spec:
      containers:
        - name: employeespring
          image: wetmonkey/spring-app:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: Employee
  ports:
  - port: 80
    protocol: TCP
  type: LoadBalancer
