apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 2
  template:
    metadata:
      labels:
        app: Employee
    spec:
      containers:
        - name: EmployeeAngular
          image: angular-app
          ports:
            - containerPort: 4200
        - name: EmployeeSpring
          image: spring-app
          ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: Employee
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  type: LoadBalancer

