apiVersion: apps/v1
kind: Deployment
metadata:
  name: angulardeployment
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 1
  template:
    metadata:
      labels:
        app: Employee
    spec:
      containers:
        - name: employeeangular
          image: wetmonkey/angular-app
          ports:
            - containerPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springdeployment
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 1
  template:
    metadata:
      labels:
        app: Employee
    spec:
        - name: employeespring
          image: wetmonkey/spring-app
          ports:
          - containerPort: 9090
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: Employee
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  type: LoadBalancer
