apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: Employee
  replicas: 2
  template:
    metadata:
      labels:
        app: Employee
    spec:
      containers:
        - name: employeeangular
          image: wetmonkey/angular-app
          ports:
            - containerPort: 4200
---
kind: Service
apiVersion: v1
metadata:
  name: angular-service
spec:
  selector:
    app: Employee
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 4200
  type: LoadBalancer
