apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentfront
spec:
  selector:
    matchLabels:
      app: Employeefront
  replicas: 1
  template:
    metadata:
      labels:
        app: Employeefront
    spec:
      containers:
        - name: employeeangular
          image: wetmonkey/angular-app-aks:latest
          ports:
            - containerPort: 4200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentback
spec:
  selector:
    matchLabels:
      app: Employeeback
  replicas: 1
  template:
    metadata:
      labels:
        app: Employeeback
    spec:
      containers:
        - name: employeespring
          image: wetmonkey/spring-app-aks:latest
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  selector:
    app: Employeefront
  ports:
  - protocol: TCP
    port: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: spring-service
spec:
  selector:
    app: Employeeback
  clusterIP: 10.0.110.10
  ports:
  - port: 9090
  type: ClusterIP
